# GLOBAL config file - all settings will be inherited by services working with the config-server
management:
  health:
    probes:
      enabled: true

#security config
azure:
  activedirectory:
    client-id: fa5cde1d-d6f8-4d13-9fa4-4d7a374cb290
    session-stateless: true

# TODO: remove the routes once https://ndph-arts.atlassian.net/browse/ARTS-636 is done
practitioner:
  service:
    endpoint:
      roles: /practitioner/roles
    name: practitioner-service
    uri: http://practitioner-service
role:
  service:
    endpoint:
      roles: /roles
    name: role-service
    uri: http://role-service
site:
  service:
    endpoint:
      sites: /sites
    name: site-service
    uri: http://site-service
