server:
  error:
    include-message: always

spring:
  main:
    # Required for the security package
    allow-bean-definition-overriding: true

mts:
  practitioner:
    name: Practitioner
    displayName: person
    attributes:
    - name: givenName
      displayName: Given Name
      validationRegex: "^[a-zA-Z]{0,35}$"
    - name: familyName
      displayName: Family Name
      validationRegex: "^[a-zA-Z]{1,35}$"
    - name: prefix
      displayName: Prefix
      validationRegex: "^[a-zA-Z]{0,35}$"
